<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Fundamentos de Linguagem Python - Do Básico a Aplicações de IA</font>
# <font color='blue'>Lista 4 de Exercícios</font>

In [1]:
# Imports
import pandas as pd
import numpy as np

#### Exercício 1: Seleção de Dados Condicional

A partir do DataFrame de funcionários abaixo, selecione e exiba apenas os funcionários do departamento de 'Vendas' que têm um salário superior a R$ 4.500.

In [2]:
# Dados de exemplo
dados = {'Nome': ['Ana', 'Bruno', 'Carla', 'Matias', 'Eliana', 'Fabiano'],
         'Departamento': ['RH', 'Vendas', 'TI', 'Vendas', 'RH', 'Vendas'],
         'Salário': [4000, 5000, 6200, 4400, 4300, 5500]}

In [3]:
# DataFrame
df_funcionarios = pd.DataFrame(dados)

In [4]:
df_funcionarios

      Nome Departamento  Salário
0      Ana           RH     4000
1    Bruno       Vendas     5000
2    Carla           TI     6200
3   Matias       Vendas     4400
4   Eliana           RH     4300
5  Fabiano       Vendas     5500

In [5]:
# Solução
mais_de_4500 = df_funcionarios[df_funcionarios['Salário'] > 4500]
print("\n--- Funcionários do departamento de 'Vendas' que têm um salário superior a R$ 4.500 ---\n")
print(mais_de_4500)
print("\n")

--- Funcionários do departamento de 'Vendas' que têm um salário superior a R$ 4.500 ---

      Nome Departamento  Salário
1    Bruno       Vendas     5000
2    Carla           TI     6200
5  Fabiano       Vendas     5500

#### Exercício 2: Agrupamento e Agregação (groupby)

Com o DataFrame de vendas abaixo, calcule o total de vendas (Valor) para cada categoria de produto.

In [6]:
# Dados de exemplo
dados_vendas = {'Categoria': ['Eletrônicos', 'Vestuário', 'Eletrônicos', 'Casa', 'Vestuário', 'Eletrônicos'],
                'Produto': ['TV', 'Camiseta', 'Notebook', 'Sofá', 'Calça', 'Celular'],
                'Valor': [2500, 80, 4500, 1500, 120, 3000]}

In [7]:
# DataFrame
df_vendas = pd.DataFrame(dados_vendas)

In [8]:
df_vendas

     Categoria   Produto  Valor
0  Eletrônicos        TV   2500
1    Vestuário  Camiseta     80
2  Eletrônicos  Notebook   4500
3         Casa      Sofá   1500
4    Vestuário     Calça    120
5  Eletrônicos   Celular   3000

In [10]:
# Solução
soma_vendas_categorias = df_vendas.groupby('Categoria')['Valor'].sum()
print("\n--- Valor Total de vendas para cada categoria de produto ---\n")
print(np.round(soma_vendas_categorias,2))
print("\n")

--- Valor Total de vendas para cada categoria de produto ---

Categoria
Casa            1500
Eletrônicos    10000
Vestuário        200
Name: Valor, dtype: int64

#### Exercício 3: Criação de Nova Coluna
<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
A partir do DataFrame de produtos abaixo, crie uma nova coluna chamada Preco_com_Desconto que contenha o valor da coluna Preco com 10% de desconto.

In [11]:
# Dados de exemplo
dados_produtos = {'Produto': ['Monitor', 'Teclado', 'Mouse', 'Webcam'],
                  'Preco': [800, 120, 70, 250]}

In [12]:
# DataFrame
df_produtos = pd.DataFrame(dados_produtos)

In [13]:
df_produtos

   Produto  Preco
0  Monitor    800
1  Teclado    120
2    Mouse     70
3   Webcam    250

In [14]:
# Solução
df_produtos['Preco_com_Desconto'] = df_produtos['Preco'].apply(lambda x: x * 0.90)
print("\n--- DataFrame com a nova coluna 'Preco_com_Desconto' ---\n")
print(df_produtos)

--- DataFrame com a nova coluna 'Preco_com_Desconto' ---

   Produto  Preco  Preco_com_Desconto
0  Monitor    800               720.0
1  Teclado    120               108.0
2    Mouse     70                63.0
3   Webcam    250               225.0

#### Exercício 4: Tratamento de Dados Ausentes (NaN)

No DataFrame de alunos abaixo, substitua as notas ausentes (NaN) pela média da turma (média da coluna 'Nota').

In [15]:
# Dados de exemplo
dados_alunos = {'Aluno': ['Alice', 'Bernardo', 'Clara', 'Marcelo'],
                'Nota': [8.5, 7.0, np.nan, 9.0]}

In [16]:
# DataFrame
df_alunos = pd.DataFrame(dados_alunos)

In [17]:
df_alunos

      Aluno  Nota
0     Alice   8.5
1  Bernardo   7.0
2     Clara   NaN
3   Marcelo   9.0

In [18]:
# Solução
# 1. Calcula a média da coluna 'Nota' (ignora o NaN automaticamente)
media_turma = df_alunos['Nota'].mean()
# 2. Substitui os valores NaN pela média calculada
df_alunos['Nota'] = df_alunos['Nota'].fillna(media_turma)
# Exibe o resultado
print(df_alunos)

      Aluno      Nota
0     Alice  8.500000
1  Bernardo  7.000000
2     Clara  8.166667
3   Marcelo  9.000000

#### Exercício 5: Ordenação de Dados (sort_values)

Ordene o DataFrame de pontuações abaixo, do maior para o menor com base na coluna 'Pontos' e exiba o resultado.

In [19]:
# Dados de exemplo
dados_pontuacao = {'Jogador': ['J1', 'J2', 'J3', 'J4', 'J5'],
                   'Pontos': [88, 95, 74, 102, 95]}

In [20]:
# DataFrame
df_pontuacao = pd.DataFrame(dados_pontuacao)

In [21]:
df_pontuacao

  Jogador  Pontos
0      J1      88
1      J2      95
2      J3      74
3      J4     102
4      J5      95

In [22]:
# Solução
# Ordena o DataFrame pela coluna 'Pontos' em ordem decrescente
df_ordenado = df_pontuacao.sort_values(by='Pontos', ascending=False)
# Exibe o resultado
print(df_ordenado)

  Jogador  Pontos
3      J4     102
4      J5      95
1      J2      95
0      J1      88
2      J3      74

#### Exercício 6: Combinação de DataFrames (merge)

Combine os DataFrames df_clientes e df_pedidos com base na coluna em comum ID_Cliente.

In [23]:
# Dados de exemplo
df_clientes = pd.DataFrame({'ID_Cliente': [1, 2, 3],
                            'Nome': ['Carlos', 'Mariana', 'Lucas']})

In [24]:
# Dados de exemplo
df_pedidos = pd.DataFrame({'ID_Pedido': [101, 102, 103],
                           'ID_Cliente': [2, 1, 2],
                           'Produto': ['Livro', 'Caneta', 'Caderno']})

In [25]:
# Solução
# Combinando os DataFrames pela coluna 'ID_Cliente'
df_combinado = pd.merge(df_clientes, df_pedidos, on='ID_Cliente')
# Exibindo o resultado
print(df_combinado)

   ID_Cliente     Nome  ID_Pedido  Produto
0           1   Carlos        102   Caneta
1           2  Mariana        101    Livro
2           2  Mariana        103  Caderno

#### Exercício 7: Manipulação de Strings (.str)
<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
No DataFrame abaixo, extraia o ano da coluna Data e crie uma nova coluna chamada Ano.

In [26]:
# Dados de exemplo
dados_eventos = {'Evento': ['Conferência A', 'Workshop B', 'Feira C'],
                 'Data': ['2025-10-25', '2026-03-12', '2026-09-01']}

In [27]:
# DataFrame
df_eventos = pd.DataFrame(dados_eventos)

In [28]:
df_eventos

          Evento        Data
0  Conferência A  2025-10-25
1     Workshop B  2026-03-12
2        Feira C  2026-09-01

In [33]:
# Solução
# 1. Converte a coluna 'Data' para o tipo datetime
df_eventos['Data'] = pd.to_datetime(df_eventos['Data'])
# 2. Extrai o ano e cria a nova coluna 'Ano'
df_eventos['Ano'] = df_eventos['Data'].dt.year
# Exibe o resultado
print(df_eventos)

          Evento       Data   Ano
0  Conferência A 2025-10-25  2025
1     Workshop B 2026-03-12  2026
2        Feira C 2026-09-01  2026

#### Exercício 8: Uso do Método apply

Crie uma nova coluna Status no DataFrame de notas. Se a Nota for maior ou igual a 7, o status deve ser 'Aprovado', caso contrário, 'Reprovado'. Use o método apply.

In [34]:
# Dados de exemplo
dados_notas = {'Aluno': ['Maria', 'Jeremias', 'Paulo', 'Roberto'],
               'Nota': [9.5, 6.0, 5.5, 8.0]}

In [35]:
# DataFrame
df_notas = pd.DataFrame(dados_notas)

In [36]:
df_notas

      Aluno  Nota
0     Maria   9.5
1  Jeremias   6.0
2     Paulo   5.5
3   Roberto   8.0

In [38]:
# Solução
condicoes = [
    df_notas['Nota'] >= 7,
    df_notas['Nota'] < 7
]
# Define os rótulos correspondentes
status = ['Aprovado', 'Reprovado']
# Cria a nova coluna
df_notas['Status'] = np.select(condicoes, status, default = "Nota não divulgada")
print(df_notas)

      Aluno  Nota     Status
0     Maria   9.5   Aprovado
1  Jeremias   6.0  Reprovado
2     Paulo   5.5  Reprovado
3   Roberto   8.0   Aprovado

#### Exercício 9: Criação de Tabela Dinâmica (pivot_table)
<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
Crie uma tabela dinâmica que mostre a soma das Vendas por Regiao e Vendedor.

In [39]:
# Dados de exemplo
dados_regional = {'Regiao': ['Norte', 'Sul', 'Norte', 'Sul', 'Norte', 'Sul'],
                  'Vendedor': ['Ana', 'Bruno', 'Ana', 'Carlos', 'Carlos', 'Bruno'],
                  'Vendas': [1000, 1500, 1200, 1800, 800, 1300]}

In [40]:
# DataFrame
df_regional = pd.DataFrame(dados_regional)

In [41]:
df_regional

  Regiao Vendedor  Vendas
0  Norte      Ana    1000
1    Sul    Bruno    1500
2  Norte      Ana    1200
3    Sul   Carlos    1800
4  Norte   Carlos     800
5    Sul    Bruno    1300

In [43]:
# Solução
# Criando uma tabela dinâmica para ver o total de vendas por Região e Vendedor
tabela_dinamica = df_regional.pivot_table(values = 'Vendas', 
                                        index = 'Regiao', 
                                        columns = 'Vendedor', 
                                        aggfunc = 'sum', 
                                        fill_value = 0)
print("\n--- Tabela Dinâmica: Total de Vendas por Região e Vendedor ---\n")
tabela_dinamica

--- Tabela Dinâmica: Total de Vendas por Região e Vendedor ---

Vendedor   Ana  Bruno  Carlos
Regiao
Norte     2200      0     800
Sul          0   2800    1800

#### Exercício 10: Análise de Séries Temporais

A partir do DataFrame de visitas a um site, selecione e exiba apenas os registros do mês de agosto de 2026.

In [44]:
# Dados de exemplo
datas = pd.to_datetime(pd.date_range(start = '2026-07-25', periods = 15, freq = 'D'))
dados_visitas = {'Visitas': [150, 165, 178, 199, 205, 210, 225, 230, 215, 240, 255, 260, 245, 250, 270]}
df_visitas = pd.DataFrame(data = dados_visitas, index = datas)
df_visitas.index.name = 'Data'

In [45]:
df_visitas

            Visitas
Data
2026-07-25      150
2026-07-26      165
2026-07-27      178
2026-07-28      199
2026-07-29      205
2026-07-30      210
2026-07-31      225
2026-08-01      230
2026-08-02      215
2026-08-03      240
2026-08-04      255
2026-08-05      260
2026-08-06      245
2026-08-07      250
2026-08-08      270

In [46]:
# Solução
# Selecionando apenas os registros de agosto de 2026
df_agosto = df_visitas.loc['2026-08']
# Exibindo o resultado
print(df_agosto)

            Visitas
Data
2026-08-01      230
2026-08-02      215
2026-08-03      240
2026-08-04      255
2026-08-05      260
2026-08-06      245
2026-08-07      250
2026-08-08      270

# Fim